### ISSUE TITLE
similar cases

### ISSUE THREAD

**Issue by nikmonios** [TEConnectivity/Weather_Shield_Arduino_Library#1]
Hello,

I noticed that case  Sensor_HTU21D and case Sensor_MS5637 send the same control signal to the Arduino board (LOW, LOW, LOW). 

Is this intentional, or is it a bug?

**Comment by williammarkezana** [comment]
Hi @nikmonios 

This is actually intentional, if you refer to the schematic available in the datasheet of the Weather Shield you can see that the HTU21D and the MS5637 are wired on the same channel of the I²C multiplexer.

![schematic](https://user-images.githubusercontent.com/20226823/30418435-39f5a35e-9933-11e7-9fa0-63d4a1f7a6be.png)

**Comment by nikmonios** [comment]
That's great!

Thank you for your prompt reply!
